SELECT * FROM T_BOARD ;
SELECT * FROM T_BOARDCOMMENT ;
SELECT * FROM T_BOARDFILE ;

-- 2번 게시글의 제목 , 작성자 닉네임 , 내용 , 댓글 내용 , 댓글 작성자

SELECT B.TITLE , U.NICKNAME , B.CONTENT , C.CONTENT , U2.NICKNAME -- ,  F.*
FROM T_BOARD B
INNER JOIN T_BOARDCOMMENT C ON C.BOARD_NO = B.BOARD_NO
INNER JOIN T_USER U ON B.ID = U.ID
INNER JOIN T_USER U2 ON U2.ID = C.ID
-- INNER JOIN T_BOARDFILE F ON F.BOARD_NO = B.BOARD_NO // 중복되서 출력되서 쿼리 밖에서 따로 빼준다
WHERE B.BOARD_NO = 2
;


